kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scoby-triggermesh-httptargets
  labels:
    scoby.triggermesh.io/crdregistration: "true"
    app.kubernetes.io/name: scoby
# Do not use this role directly. These rules will be added to the "crd-registrations-scoby" role.
rules:

# Component
- apiGroups:
  - targets.triggermesh.io
  resources:
  - httptargets
  verbs:
  - get
  - list
  - watch
  - update
# Status
- apiGroups:
  - targets.triggermesh.io
  resources:
  - httptargets/status
  verbs:
  - get
  - update
  - patch

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scoby-triggermesh-httptargets-addressable
  labels:
    app.kubernetes.io/part-of: triggermesh
    duck.knative.dev/addressable: 'true'
rules:
# +rbac-check
- apiGroups:
  - targets.triggermesh.io
  resources:
  - httptargets
  verbs:
  - get
  - list
  - watch


