apiVersion: scoby.triggermesh.io/v1alpha1
kind: CRDRegistration
metadata:
  name: httptarget
spec:
  crd: httptargets.targets.triggermesh.io
  workload:
    fromImage:
      repo: gcr.io/triggermesh/httptarget-adapter:v1.25.0
    formFactor:
      deployment:
        replicas: 1
        service:
          port: 80
          targetPort: 8080
    parameterConfiguration:
      global:
        defaultPrefix: HTTP_

      add:
        toEnv:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K_METRICS_CONFIG
          value: "{}"
        - name: K_LOGGING_CONFIG
          value: "{}"

      fromSpec:
        toEnv:
        - path: spec.response.eventType
          name: HTTP_EVENT_TYPE
        - path: spec.response.eventSource
          name: HTTP_EVENT_SOURCE
          defaultValue: httptarget
        - path: spec.endpoint
          name: HTTP_URL
        - path: spec.method
          name: HTTP_METHOD
        - path: spec.skipVerify
          name: HTTP_SKIP_VERIFY
        - path: spec.caCertificate
          name: HTTP_CA_CERTIFICATE
        - path: spec.basicAuthUsername
          name: HTTP_BASICAUTH_USERNAME
        - path: spec.basicAuthPassword
          name: HTTP_BASICAUTH_PASSWORD
          valueFrom:
            secret:
              name: spec.credentials.name
              key: spec.preferences.key
        - path: spec.oauthClientID
          name: HTTP_OAUTH_CLIENT_ID
        - path: spec.oauthClientSecret
          name: HTTP_OAUTH_CLIENT_SECRET
          valueFrom:
            secret:
              name: spec.credentials.name
              key: spec.preferences.key
        - path: spec.oauthTokenURL
          name: HTTP_OAUTH_TOKEN_URL
        - path: spec.oauthScopes
          name: HTTP_OAUTH_SCOPE
        - path: spec.headers
          name: HTTP_HEADERS
