apiVersion: scoby.triggermesh.io/v1alpha1
kind: CRDRegistration
metadata:
  name: kuard
spec:
  crd: kuards.extensions.triggermesh.io
  workload:
    formFactor:
      deployment:
        replicas: 1
        service:
          port: 80
          targetPort: 8080

    fromImage:
      repo: gcr.io/kuar-demo/kuard-amd64:blue

    parameterConfiguration:
      fromSpec:
        toEnv:
        # Resolve an address
        - path: spec.refToAddress
          name: FOO_SINK
          valueFrom:
            builtInFunc:
              name: resolveAddress
    statusConfiguration:
      addElements:
      # Add the result to an status element
      - path: status.sinkUri
        render:
          valueFromParameter:
            path: spec.refToAddress
