apiVersion: scoby.triggermesh.io/v1alpha1
kind: CRDRegistration
metadata:
  name: httppollersource
spec:
  crd: httppollersources.sources.triggermesh.io
  workload:
    fromImage:
      repo: gcr.io/triggermesh/httppollersource-adapter:v1.25.0
    formFactor:
      deployment:
        replicas: 1
    parameterConfiguration:
      global:
        defaultPrefix: HTTPPOLLER_

      add:
        toEnv:
        - name: METRICS_DOMAIN
          value: triggermesh.io/sources
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K_METRICS_CONFIG
          value: "{}"
        - name: K_LOGGING_CONFIG
          value: "{}"

      fromSpec:
        toEnv:
        - path: spec.eventType
          name: HTTPPOLLER_EVENT_TYPE
        - path: spec.eventSource
          name: HTTPPOLLER_EVENT_SOURCE
        - path: spec.sink
          name: K_SINK
          valueFrom:
            builtInFunc:
              name: resolveAddress
