apiVersion: scoby.triggermesh.io/v1alpha1
kind: CRDRegistration
metadata:
  name: kafkatarget
spec:
  crd: kafkatargets.targets.triggermesh.io
  workload:
    fromImage:
      repo: gcr.io/triggermesh/kafkatarget-adapter:v1.25.0
    formFactor:
      deployment:
        replicas: 1
        service:
          port: 80
          targetPort: 8080
    parameterConfiguration:

      addEnvs:
      - name: METRICS_DOMAIN
        value: triggermesh.io/targets
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: K_METRICS_CONFIG
        value: "{}"
      - name: K_LOGGING_CONFIG
        value: "{}"

      specToEnvs:
      - path: spec.bootstrapServers
        render:
          name: BOOTSTRAP_SERVERS

      - path: spec.topic
        render:
          name: TOPIC

      - path: spec.topicReplicationFactor
        render:
          name: TOPIC_REPLICATION_FACTOR

      - path: spec.topicPartitions
        render:
          name: TOPIC_PARTITIONS

      - path: spec.discardCloudEventContext
        render:
          name: DISCARD_CE_CONTEXT

      - path: spec.auth.saslEnable
        render:
          name: SASL_ENABLE

      - path: spec.auth.securityMechanism
        render:
          name: SECURITY_MECHANISMS

      - path: spec.auth.tlsEnable
        render:
          name: TLS_ENABLE

      - path: spec.auth.tls.skipVerify
        render:
          name: SKIP_VERIFY

      - path: spec.auth.tls.ca
        render:
          name: CA
          valueFromSecret:
            name: spec.auth.tls.ca.valueFromSecret.name
            key: spec.auth.tls.ca.valueFromSecret.key

      - path: spec.auth.tls.clientCert
        render:
          name: CLIENT_CERT
          valueFromSecret:
            name: spec.auth.tls.clientCert.valueFromSecret.name
            key: spec.auth.tls.clientCert.valueFromSecret.key

      - path: spec.auth.tls.clientKey
        render:
          name: CLIENT_KEY
          valueFromSecret:
            name: spec.auth.tls.clientKey.valueFromSecret.name
            key: spec.auth.tls.clientKey.valueFromSecret.key

      - path: spec.auth.username
        render:
          name: USERNAME

      - path: spec.auth.password
        render:
          name: PASSWORD
          valueFromSecret:
            name: spec.auth.password.valueFromSecret.name
            key: spec.auth.password.valueFromSecret.key


# MISSING
# KerberosConfigPath  string `envconfig:"KERBEROS_CONFIG_PATH" required:"false" `
# KerberosServiceName string `envconfig:"KERBEROS_SERVICE_NAME" required:"false" `
# KerberosKeytabPath  string `envconfig:"KERBEROS_KEYTAB_PATH" required:"false"`
# KerberosRealm       string `envconfig:"KERBEROS_REALM" required:"false"`
# KerberosUsername    string `envconfig:"KERBEROS_USERNAME" required:"false"`
# KerberosPassword    string `envconfig:"KERBEROS_PASSWORD" required:"false"`



# NOT IMPLEMENTED
# ConnectionRefreshPeriod time.Duration `envconfig:"CONNECTION_REFRESH_PERIOD" default:"5m"`
# // This set of variables are experimental and not graduated to the CRD.
# CreateTopicIfMissing        bool  `envconfig:"CREATE_MISSING_TOPIC" default:"true"`
# FlushOnExitTimeoutMillisecs int   `envconfig:"FLUSH_ON_EXIT_TIMEOUT_MS" default:"10000"`
# CreateTopicTimeoutMillisecs int   `envconfig:"CREATE_TOPIC_TIMEOUT_MS" default:"10000"`

# NewTopicPartitions          int32 `envconfig:"TOPIC_PARTITIONS" default:"1"`
# NewTopicReplicationFactor   int16 `envconfig:"TOPIC_REPLICATION_FACTOR" default:"1"`

# DiscardCEContext bool `envconfig:"DISCARD_CE_CONTEXT"`