apiVersion: scoby.triggermesh.io/v1alpha1
kind: CRDRegistration
metadata:
  name: webhooksource
spec:
  crd: webhooksources.sources.triggermesh.io
  workload:
    fromImage:
      repo: gcr.io/triggermesh/webhooksource-adapter:v1.25.0
    formFactor:
      deployment:
        replicas: 1
        service:
          port: 80
          targetPort: 8080

    parameterConfiguration:
      global:
        defaultPrefix: WEBHOOK_

      add:
        toEnv:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K_METRICS_CONFIG
          value: "{}"
        - name: K_LOGGING_CONFIG
          value: "{}"

      fromSpec:
        toEnv:
        - path: spec.eventType
          name: WEBHOOK_EVENT_TYPE
        - path: spec.eventSource
          name: WEBHOOK_EVENT_SOURCE
        - path: spec.basicAuthUsername
          name: WEBHOOK_BASICAUTH_USERNAME
        - path: spec.basicAuthPassword
          name: WEBHOOK_BASICAUTH_PASSWORD
          valueFrom:
            secretPath:
              name: spec.basicAuthPassword.valueFromSecret.name
              key: spec.basicAuthPassword.valueFromSecret.key
        - path: spec.eventExtensionAttributes.from
          name: WEBHOOK_EVENT_EXTENSION_ATTRIBUTES_FROM
        - path: spec.corsAllowOrigin
          name: WEBHOOK_CORS_ALLOW_ORIGIN
        - path: spec.sink
          name: K_SINK
          valueFrom:
            builtInFunc:
              name: resolveAddress

    statusConfiguration:
      add:
      - path: status.sinkUri
        valueFrom:
          path: spec.sink
