apiVersion: scoby.triggermesh.io/v1alpha1
kind: CRDRegistration
metadata:
  name: webhooksource
spec:
  crd: webhooksources.sources.triggermesh.io
  workload:
    fromImage:
      repo: gcr.io/triggermesh/webhooksource-adapter:v1.25.0
    formFactor:
      deployment:
        replicas: 1
        service:
          port: 80
          targetPort: 8080

    parameterConfiguration:
      global:
        defaultPrefix: WEBHOOK_

      addEnvs:
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: K_METRICS_CONFIG
        value: "{}"
      - name: K_LOGGING_CONFIG
        value: "{}"

      fromSpec:
      - path: spec.eventType
        toEnv:
          name: WEBHOOK_EVENT_TYPE

      - path: spec.eventSource
        toEnv:
          name: WEBHOOK_EVENT_SOURCE

      - path: spec.basicAuthUsername
        toEnv:
          name: WEBHOOK_BASICAUTH_USERNAME

      - path: spec.basicAuthPassword
        toEnv:
          name: WEBHOOK_BASICAUTH_PASSWORD
          valueFromSecret:
            name: spec.basicAuthPassword.valueFromSecret.name
            key: spec.basicAuthPassword.valueFromSecret.key

      - path: spec.eventExtensionAttributes.from
        toEnv:
          name: WEBHOOK_EVENT_EXTENSION_ATTRIBUTES_FROM

      - path: spec.corsAllowOrigin
        toEnv:
          name: WEBHOOK_CORS_ALLOW_ORIGIN

      - path: spec.sink
        toEnv:
          name: K_SINK
          valueFromBuiltInFunc:
            name: resolveAddress

    statusConfiguration:
      addElements:
      - path: status.sinkUri
        render:
          valueFromParameter:
            path: spec.sink
