kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scoby-triggermesh-kafkasources
  labels:
    scoby.triggermesh.io/crdregistration: "true"
    app.kubernetes.io/name: scoby
# Do not use this role directly. These rules will be added to the "crd-registrations-scoby" role.
rules:

# Source
- apiGroups:
  - sources.triggermesh.io
  resources:
  - kafkasources
  verbs:
  - get
  - list
  - watch
  - update
# Status
- apiGroups:
  - sources.triggermesh.io
  resources:
  - kafkasources/status
  verbs:
  - get
  - update
  - patch



