apiVersion: scoby.triggermesh.io/v1alpha1
kind: CRDRegistration
metadata:
  name: kuard
spec:
  crd: kuards.extensions.triggermesh.io
  workload:
    formFactor:
      deployment:
        replicas: 1
        service:
          port: 80
          targetPort: 8080

    fromImage:
      repo: gcr.io/kuar-demo/kuard-amd64:blue

    parameterConfiguration:
      fromSpec:
        toEnv:
        # Reference a secret
        - path: spec.refToSecret
          name: FOO_CREDENTIALS
          valueFrom:
            secretPath:
              name: spec.refToSecret.secretName
              key: spec.refToSecret.secretKey

